### ISSUE TITLE
Feature Request - Move to project

### ISSUE THREAD

**Issue by guptaanmol184** [reisub0/nzb#2]
I have been using nzb for the last two days and it has helped me a lot in getting things done.

The only thing that I have to go to the webapp is for moving items from the Inbox to specific lists. It will be a handy feature if we could move items from Inbox to any other specific project.

**Comment by autolyticus** [comment]
`nzb done nzb mv`

The latest version (v0.5.0) [10774ae016c9a7764c085aa25ea165f0f4e1e066] has implemented this feature.
Thanks for the suggestion!
