### ISSUE TITLE
Open sponsorship

### ISSUE THREAD

**Issue by limakzi** [reisub0/nzb#3]
Hi!
I love this project. Be so kind and allow Sponsorship for it.
Thanks.

**Comment by autolyticus** [comment]
Hi @limakzi 

I'm so glad to hear that you love nzb and that you want to support the project! I'm understanding Sponsorship to mean Github Sponsorships which is still in beta and direct payments aren't supported in my country. 

I'm a student and I'm doing this in my free time and I'm so happy to hear that someone from the other side of the world found my little cli app useful. The happiness is more than enough for me!

I'd love it if you could please donate to your favourite charity instead!

Love and regards

**Comment by limakzi** [comment]
Will do! Appreciate this project. I can help making a package for Homebrew if you wish.
Donation for charity will be placed, for sure.
